language: cpp
compiler:
  - clang
env:
  matrix: 
    - JULIAVERSION="juliareleases" 
    - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("ReinforcementLearning"))`); Pkg.pin("ReinforcementLearning"); Pkg.clone("https://github.com/dcjones/Showoff.jl"); Pkg.checkout("Gadfly"); Pkg.resolve()'
  - julia -e 'using ReinforcementLearning; @assert isdefined(:ReinforcementLearning); @assert typeof(ReinforcementLearning) === Module'
  - julia --code-coverage ./test/runtests.jl
after_success:
  - julia -e 'cd(Pkg.dir("ReinforcementLearning")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
